language: php
php:
  - 8.0
  - 8.1
  - 8.2
  - 8.4
 
services:
  - mysql
 
install:
  - composer install --no-interaction --prefer-dist
 
before_script:
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --seed
 
script:
  - vendor/bin/phpunit
 